"""init

Revision ID: 693bade08712
Revises: 
Create Date: 2025-08-28 00:59:26.318207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '693bade08712'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detalle_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('numero_serie', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalle_venta_id'), 'detalle_venta', ['id'], unique=False)
    op.create_table('devoluciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.String(), nullable=True),
    sa.Column('estado_producto', sa.String(), nullable=True),
    sa.Column('fecha', sa.String(), nullable=True),
    sa.Column('autorizado_por', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devoluciones_id'), 'devoluciones', ['id'], unique=False)
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_barras', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('numero_serie', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_serie')
    )
    op.create_index(op.f('ix_productos_codigo_barras'), 'productos', ['codigo_barras'], unique=True)
    op.create_index(op.f('ix_productos_id'), 'productos', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('rol', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.String(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('estado_caja', sa.String(), nullable=True),
    sa.Column('metodo_pago', sa.String(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ventas_id'), 'ventas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ventas_id'), table_name='ventas')
    op.drop_table('ventas')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_productos_id'), table_name='productos')
    op.drop_index(op.f('ix_productos_codigo_barras'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_devoluciones_id'), table_name='devoluciones')
    op.drop_table('devoluciones')
    op.drop_index(op.f('ix_detalle_venta_id'), table_name='detalle_venta')
    op.drop_table('detalle_venta')
    # ### end Alembic commands ###
