version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: electrostore
      POSTGRES_PASSWORD: electrostorepass
      POSTGRES_DB: electrostore
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  electrostore-api:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://electrostore:electrostorepass@db:5432/electrostore
      - SECRET_KEY=electrostore_secret_key

volumes:
  pgdata:
  electrostore-data:
